### ISSUE TITLE
Enregistrer un son depuis la version web

### ISSUE THREAD

**Issue by Crali** [kevin-verschaeve/boite-a-beauf#2]
Permettre l'enregistrement d'un son depuis l'interface web.
Le son enregistré sera placé dans le dossier "records".
Le son enregistré sera en attente de validation avant de pouvoir être lu.

Créer un sous dossier dans "records" > "waiting" ?
Ajouter un préfixe au nom du fichier en attente de validation puis le retirer lorsque validé ? Ex : waiting_miaou.wav > validation > miaou.wav ?

**Comment by kevin-verschaeve** [comment]
juste pour note:
https://stackoverflow.com/questions/16413063/html5-record-audio-to-file
